<a href="https://colab.research.google.com/github/joaoSouza2121/intro-pytorch/blob/main/Intro_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Machine Learning

##Introdução ao Framework PyTorch
A computação em modelos de Deep Learning é feita com tensores, que são generalizações de uma matriz que pode ser indexada em mais de duas dimensões. O PyTorch é um framework que aplica operações matemáticas a tensores para então treinar modelos de Deep Learning.

https://pytorch.org/

TorchScript

O PyTorch TorchScript ajuda a criar modelos serializáveis e otimizáveis. Depois que treinamos esses modelos, eles também podem ser executados independentemente. Isso ajuda quando estamos no estágio de implantação do modelo de um projeto de Data Science.

Você pode treinar um modelo no PyTorch usando Python e depois exportá-lo via TorchScript para um ambiente de produção em que Python não esteja disponível.

Treinamento Distribuído

O PyTorch também oferece suporte a treinamento distribuído que permite que pesquisadores e profissionais paralelizem seus cálculos. O treinamento distribuído possibilita o uso de várias GPUs para processar lotes maiores de dados de entrada. Isso, por sua vez, reduz o tempo de computação.

Suporte para Python

O PyTorch tem uma interação muito boa com o Python. De fato, a codificação no PyTorch é bastante semelhante ao que fazemos em Python. 

In [1]:
# Imports
import numpy
import torch
import torchvision

##Criando e Manipulando Tensores
A razão pela qual usamos o Numpy em Machine Learning é que é muito mais rápido do que as listas Python na execução de operações de matriz.

Por quê? Internamente, NumPy faz a maior parte do trabalho pesado em Linguagem C, que é muito mais veloz que Python.

Mas, no caso de treinar redes neurais profundas (Deep Learning), os arrays NumPy levariam meses para treinar algumas das redes de ponta. É aqui que os tensores entram em cena. O PyTorch nos fornece uma estrutura de dados chamada Tensor, que é muito semelhante à matriz ND do NumPy. Mas, diferentemente do último, os tensores podem aproveitar os recursos de uma GPU para acelerar significativamente as operações com matrizes.

In [2]:
# Criando um tensor
x = torch.tensor([1., 2.])
print(x)

tensor([1., 2.])


In [3]:
# shape
print(x.shape)

torch.Size([2])


In [4]:
# Criando um tensor
t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]], dtype = torch.float32)


Para determinar a forma desse tensor, examinamos primeiro as linhas (3) e depois as colunas (4). Portanto, esse tensor é 3 x 4 de classificação (rank) 2.

Rank é uma palavra comumente usada e significa apenas o número de dimensões presentes no tensor.

No PyTorch, temos duas maneiras de obter a forma (shape):

In [5]:
t.size()

torch.Size([3, 4])

In [6]:
t.shape

torch.Size([3, 4])

No PyTorch, o tamanho e a forma de um tensor significam a mesma coisa.

Normalmente, depois de conhecermos a forma de um tensor, podemos deduzir algumas coisas. Primeiro, podemos deduzir o rank do tensor. O rank de um tensor é igual ao comprimento da forma do tensor.

In [7]:
len(t.shape)

2

In [8]:
len(x.shape)

1

Podemos deduzir o numero de elementos contidos no tensor. o numero de elementos dentro de um tenor (12 no caso de tensor t e 2 no tensor x) é igual ao produto dos valores dos componentes da forma.

In [9]:
torch.tensor(t.shape).prod()

tensor(12)

In [10]:
torch.tensor(x.shape).prod()

tensor(2)

In [11]:
# Retornando um elemento de um tensor
z = torch.tensor([[1., 2.],[5., 3.],[0., 4.]])


In [12]:
print(z)

tensor([[1., 2.],
        [5., 3.],
        [0., 4.]])


In [13]:
# shape
print(z.shape)

torch.Size([3, 2])


In [14]:
# retorna a primeira linha (indice 0) e segunda coluna (indice 1) -> o retorno e no formato de tensor
print(z[0][1].item())

2.0


Quando criamos tensores com valores randomicos, passamos apenas o numero de dimensoes.

In [15]:
input1 = torch.randn([1, 4, 4, 2])
input2 = torch.randn([1, 4, 4, 2])

In [16]:
# shape
print(input1.shape)
print(input2.shape)

torch.Size([1, 4, 4, 2])
torch.Size([1, 4, 4, 2])


In [17]:
print(len(input1.shape))
print(len(input2.shape))

4
4


In [18]:
input1

tensor([[[[ 0.8719, -1.2321],
          [-0.5157,  0.3500],
          [ 0.3006,  0.1319],
          [ 1.1096, -0.8107]],

         [[-0.4726,  1.0526],
          [ 0.5524,  0.4249],
          [ 0.3507,  0.8626],
          [ 0.6871, -0.5404]],

         [[-0.2267,  1.2610],
          [-0.2503,  0.4283],
          [ 0.2513, -0.6923],
          [ 0.3893, -0.5348]],

         [[-0.1066, -0.9158],
          [-0.5271, -0.9731],
          [ 0.0313,  0.2358],
          [-0.0831,  0.7130]]]])

In [19]:
input2

tensor([[[[-1.5614,  0.3779],
          [-0.2217, -1.6525],
          [ 1.2993,  0.2632],
          [-0.0389,  0.6123]],

         [[ 0.7503, -1.5615],
          [ 0.8205, -1.6762],
          [-0.1738, -0.6095],
          [-2.1071,  1.9696]],

         [[-1.2782, -0.0621],
          [-1.2265, -1.0696],
          [ 0.8437,  0.0262],
          [-0.2149,  0.5839]],

         [[ 0.9943, -1.7522],
          [-0.2523, -0.2926],
          [ 0.8634, -0.9480],
          [-0.5530,  0.5996]]]])

Considere tensores como número de listas que uma dimensão contém. por exemplo, um tensor(1, 4, 4, 2) terá:

1 lista contendo 4 elementos de 4 elementos de 2 elementos

  . A primeira dimensão pode conter 1 elemento.

  . A segunda dimensão pode conter 4 elemento.

  . A terceira dimensão pode conter 4 elemento.
  
  . A quarta dimensão pode conter 2 elemento.

##Array NumPy x Tensor PyTorch

In [20]:
# Numpy array
a = numpy.array(1)
# Pytorch
b = torch.tensor(1)

In [21]:
# type
type(a)

numpy.ndarray

In [22]:
type(b)

torch.Tensor

In [23]:
print(a)
print(b)

1
tensor(1)


## Operações com Tensores

In [24]:
t1 = torch.tensor(12)
t2 = torch.tensor(4)
print(t1)
print(t2)

tensor(12)
tensor(4)


In [25]:
# soma
print(t1 + t2)
# subtração
print(t1 - t2)

tensor(16)
tensor(8)


In [26]:
# multiplicação
print(t1 * t2)
# divisao
print(t1 // t2)

tensor(48)
tensor(3)


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)


## Operações com Matrizes

In [27]:
# Matriz (tensor rank 2) de numeros randomicos
t_rank2 = torch.randn(3,3)
t_rank2

tensor([[ 1.0691,  0.9017,  0.4375],
        [ 0.2036, -1.0476, -0.3142],
        [-0.3791, -1.1183, -0.8081]])

In [28]:
# Matriz (tensor rank 3) de numeros randomicos
t_rank3 = torch.randn(3,3,3)
t_rank3

tensor([[[ 0.0462, -0.4828, -1.6350],
         [ 0.3295, -1.3484,  1.5081],
         [ 0.9853,  0.5514, -0.8245]],

        [[ 0.3276, -1.0132,  1.0975],
         [-2.5345, -1.5911,  0.8066],
         [ 0.2183,  2.8317, -0.6591]],

        [[-1.1804, -0.9621,  0.1837],
         [-1.3123, -0.1546,  0.2192],
         [-0.9843,  1.5976, -0.9578]]])

In [29]:
# Matriz (tensor rank 4) de numeros randomicos
t_rank4 = torch.randn(3,3,3,3)
t_rank4

tensor([[[[ 0.5430, -0.1201,  0.2736],
          [ 0.8281,  0.7519,  0.9619],
          [ 0.3815,  1.2447, -0.4777]],

         [[ 0.2743, -1.7100, -0.0835],
          [-1.1392,  0.5190, -1.4369],
          [ 0.6250,  0.8036, -0.0686]],

         [[-2.4140,  0.6513, -0.1174],
          [-0.0174,  0.6948, -1.0731],
          [-0.3198, -0.7364,  0.4290]]],


        [[[-1.4422,  1.3562, -0.7337],
          [-1.1256,  0.5969,  0.9830],
          [ 1.1538,  2.5647,  1.7782]],

         [[ 0.8020, -0.1177,  0.6923],
          [-0.3840, -1.2216,  1.3025],
          [-0.0170, -0.2320, -0.5935]],

         [[-0.2886, -1.9042, -1.9643],
          [ 0.2283,  0.4676,  0.4810],
          [-1.5127, -0.7565,  0.8881]]],


        [[[ 0.5510,  0.7444, -1.3514],
          [ 0.4240, -1.1568,  0.9911],
          [ 1.2233,  2.2147, -0.7106]],

         [[ 1.3184,  0.1809,  0.9534],
          [ 0.4565,  0.0981,  1.2337],
          [ 0.0438, -0.3697, -1.3200]],

         [[-0.5134,  0.6400,  1.4618],
     

In [30]:
# Multiplicação entre 2 tensores
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])


In [31]:
A.shape

torch.Size([3, 3])

In [32]:
B.shape

torch.Size([3, 3])

In [33]:
resultado1 = A * B
print(resultado1)

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])


In [34]:
resultado2 = torch.matmul(A, B)
print(resultado2)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [35]:
resultado3 = torch.sum(A * B)
print(resultado3)

tensor(165)


Para multiplicação de matrizes, fazemos assim em PyTorch

In [36]:
AB1 = A.mm(B)
# ou
AB2 = torch.mm(A, B)
# ou
AB3 = torch.matmul(A, B)
# Ou assim (Python 3.5+)
AB4 = A @ B

In [37]:
print(AB1)
print(AB2)
print(AB3)
print(AB4) 

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [38]:
# Multiplicação de matrizes
A @ B

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

Essa notação realiza multiplicação element-wise:

In [39]:
A * B

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

In [40]:
# Usando seed para iniciar 2 tensores com valores randômicos
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [41]:
# Adição de matrizes
print(torch.add(a, b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [42]:
# subtração de matrizes
print(torch.sub(a, b))

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [43]:
# multiplicação de matrizes
print(torch.mm(a, b))

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [44]:
# divisão de matrizes
print(torch.div(a, b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [45]:
# matriz original
print(a, '\n')

# transposta da matriz
print(torch.t(a))

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])
